version: "3.9"

services:
  my-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: eagle-bot-api-automation
    image: sudharsanmaran/eagle-bot-api-automation:v1.0
    restart: on-failure

    ports:
      - "8002:8002"
      - "5678:5678"

    volumes:
      - .:/app

    env_file:
      - .env